version: "3.5"

services:
  nextcloud-app:
    container_name: nextcloud-app
    image: nextcloud:28
    depends_on: 
      - nextcloud-db
    restart: unless-stopped
    networks:
      - internal_network
      - ${NGINX_PROXY_NETWORK}
    volumes:
      - ${APP_DIR}:/var/www/html
      - ${DATA_DIR}:/var/www/html/data
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: ${DOMAIN_NAME} # required to get rid of "untrusted domains" error
      NEXTCLOUD_DATA_DIR: /var/www/html/data
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      OVERWRITEPROTOCOL: https # required to authorize Nextcloud apps
      MYSQL_HOST: nextcloud-db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      # The following settings allow this container to work with nginx-proxy and acme-companion
      VIRTUAL_HOST: ${DOMAIN_NAME}
      LETSENCRYPT_HOST: ${DOMAIN_NAME}
      VIRTUAL_PORT: 80

  nextcloud-db:
    container_name: nextcloud-db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    restart: unless-stopped
    networks:
      - internal_network
    volumes:
      - ${DB_DIR}:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

networks:
  internal_network:
  nginx_network:
    name: ${NGINX_PROXY_NETWORK}
    external: true 
