version: "3.5"

services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on: 
      - nextcloud-db
    restart: always
    networks:
      - internal_network
      - nginx_network
    volumes:
      - ${HOST_CONFIG_DIR}:/var/www/html/config
      - ${HOST_DATA_DIR}:/var/www/html/data
    environment:
      PUID: ${PUID}
      GUID: ${GUID}
      NEXTCLOUD_TRUSTED_DOMAINS: ${HOST_NAME} # required to get rid of "untrusted domains" error
      NEXTCLOUD_DATA_DIR: /var/www/html/data
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      OVERWRITEPROTOCOL: https # required to authorize Nextcloud apps
      MYSQL_HOST: nextcloud-db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      # The following settings allow this container to work with nginx-proxy and acme-companion
      VIRTUAL_HOST: ${HOST_NAME}
      LETSENCRYPT_HOST: ${HOST_NAME}
      VIRTUAL_PORT: 80

  nextcloud-db:
    container_name: nextcloud-db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    restart: always
    networks:
      - internal_network
    volumes:
      - ${HOST_DB_DIR}:/var/lib/mysql
    environment:
      PUID: ${PUID}
      GUID: ${GUID}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

networks:
  internal_network:
  nginx_network:
    external: true 
